In [ ]:
import pandas as pd

production=pd.Series(
    [30,60,45,25],
    index=["wheat","rice","maize","barley"]
)
print(production)

wheat     30
rice      60
maize     45
barley    25
dtype: int64

In [ ]:
print(production["rice"])
print(production.loc["rice"])

60
60

In [ ]:
print(production.iloc[0])

30

In [ ]:
print(production.sum())
print(production.mean())
print(production.max())

160
40.0
60

In [ ]:
print(production.idxmax())

rice

In [ ]:
in_production=production*1.10
print(in_production)

wheat     33.0
rice      66.0
maize     49.5
barley    27.5
dtype: float64

In [ ]:
print(production>40)

wheat     False
rice       True
maize      True
barley    False
dtype: bool

In [ ]:
high_production=production[production>40]
print(high_production)

rice     60
maize    45
dtype: int64

In [ ]:
df=pd.DataFrame({
    "name":["akhil","Jane","Bob"],
    "age":[25,30,35],
    "city":["aaa","bbb","ccc"]
},index= ["a","b","c"])
print(df)
print()
print(df.loc["b"])

    name  age city
a  akhil   25  aaa
b   Jane   30  bbb
c    Bob   35  ccc

name    Jane
age       30
city     bbb
Name: b, dtype: object

In [ ]:
print(df.loc[["a","c"],["name","age"]])

    name  age
a  akhil   25
c    Bob   35

In [ ]:
print
df.loc["a":"c"]

    name  age city
a  akhil   25  aaa
b   Jane   30  bbb
c    Bob   35  ccc

In [3]:
import pandas as pd
df=pd.DataFrame({
    "name":["akhil","Jane","Bob"],
    "age":[25,30,35],
    "city":["aaa","bbb","ccc"]
},index= ["a","b","c"])
print(df.loc[df["age"]>28,["name","age"]])

   name  age
b  Jane   30
c   Bob   35

In [4]:
print(df.iloc[0:2])

    name  age city
a  akhil   25  aaa
b   Jane   30  bbb

In [6]:
print(df.iloc[[0,2]])

    name  age city
a  akhil   25  aaa
c    Bob   35  ccc

In [7]:
df["name"]

a    akhil
b     Jane
c      Bob
Name: name, dtype: object

In [9]:
df[["name","age"]]

    name  age
a  akhil   25
b   Jane   30
c    Bob   35

In [15]:
import pandas as pd
data={
    "farm":["farm A","farm B","farm C","farm D"],
      "CROP":["wheat","rice","maize","barley"],
      "AREA":[10,15,8,12],
      "production":[30,60,45,25],
}
df=pd.DataFrame(data)
print(df)

     farm    CROP  AREA  production
0  farm A   wheat    10          30
1  farm B    rice    15          60
2  farm C   maize     8          45
3  farm D  barley    12          25

In [16]:
df.head()

     farm    CROP  AREA  production
0  farm A   wheat    10          30
1  farm B    rice    15          60
2  farm C   maize     8          45
3  farm D  barley    12          25

In [17]:
df.head(2)

     farm   CROP  AREA  production
0  farm A  wheat    10          30
1  farm B   rice    15          60

In [18]:
df.tail()

     farm    CROP  AREA  production
0  farm A   wheat    10          30
1  farm B    rice    15          60
2  farm C   maize     8          45
3  farm D  barley    12          25

In [19]:
df.tail(2)

     farm    CROP  AREA  production
2  farm C   maize     8          45
3  farm D  barley    12          25

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   farm        4 non-null      object
 1   CROP        4 non-null      object
 2   AREA        4 non-null      int64
 3   production  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [21]:
df.describe()

            AREA  production
count   4.000000    4.000000
mean   11.250000   40.000000
std     2.986079   15.811388
min     8.000000   25.000000
25%     9.500000   28.750000
50%    11.000000   37.500000
75%    12.750000   48.750000
max    15.000000   60.000000

In [23]:
df["yield_ton_per_ha"]=df["production"]/df["AREA"]
print(df)

     farm    CROP  AREA  production  yield_ton_per_ha
0  farm A   wheat    10          30          3.000000
1  farm B    rice    15          60          4.000000
2  farm C   maize     8          45          5.625000
3  farm D  barley    12          25          2.083333

In [25]:
print(df.iloc[1:4:2])

     farm    CROP  AREA  production  yield_ton_per_ha
1  farm B    rice    15          60          4.000000
3  farm D  barley    12          25          2.083333

In [27]:
print(df.iloc[[1,3]])

     farm    CROP  AREA  production  yield_ton_per_ha
1  farm B    rice    15          60          4.000000
3  farm D  barley    12          25          2.083333

In [28]:
print(df.iloc[[1,3],[0,1,2]])

     farm    CROP  AREA
1  farm B    rice    15
3  farm D  barley    12

In [31]:
print(df['CROP']=="wheat")
print()
wheat_farm=df[df["CROP"]=="wheat"]
print(wheat_farm)

0     True
1    False
2    False
3    False
Name: CROP, dtype: bool

     farm   CROP  AREA  production  yield_ton_per_ha
0  farm A  wheat    10          30               3.0

In [33]:
high_yield=df[df["yield_ton_per_ha"]>3]
print(high_yield)

     farm   CROP  AREA  production  yield_ton_per_ha
1  farm B   rice    15          60             4.000
2  farm C  maize     8          45             5.625

In [37]:
sort=df.sort_values(by="yield_ton_per_ha",ascending=False)
print(sort)

     farm    CROP  AREA  production  yield_ton_per_ha
2  farm C   maize     8          45          5.625000
1  farm B    rice    15          60          4.000000
0  farm A   wheat    10          30          3.000000
3  farm D  barley    12          25          2.083333

In [39]:
avg_yield=df.groupby("CROP")["yield_ton_per_ha"].mean()
print(avg_yield)

CROP
barley    2.083333
maize     5.625000
rice      4.000000
wheat     3.000000
Name: yield_ton_per_ha, dtype: float64

In [41]:
sum_yield=df.groupby("CROP")["yield_ton_per_ha"].sum()
print(sum_yield)

CROP
barley    2.083333
maize     5.625000
rice      4.000000
wheat     3.000000
Name: yield_ton_per_ha, dtype: float64